apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
  labels:
    app: html-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-app
  # === Configuración de estrategia de actualización (NUEVO) ===
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1  # Máximo de pods no disponibles durante la actualización
      maxSurge: 1        # Máximo de pods adicionales durante la actualización
  template:
    metadata:
      labels:
        app: html-app
    spec:
      # === Tiempo de gracia para terminar pods (NUEVO) ===
      terminationGracePeriodSeconds: 30  # 30 segundos (valor por defecto)
      containers:
      - name: nginx
        image: liyo13/build-push-actions
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service
spec:
  selector:
    app: hello-world  # ¡OJO! Debe coincidir con el label del Deployment (app: html-app)
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
