# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
  labels:
    app: html-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: html-app
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      # Nombre del contenedor actualizado para mayor claridad
      - name: httpd-container 
        # Esta imagen es solo un placeholder, el pipeline la reemplazará
        image: httpd:alpine 
        ports:
        - containerPort: 80
