# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-app
  labels:
    app: html-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: html-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: html-app
    spec:
      # === PASO NUEVO: AÑADIR EL SECRETO PARA DESCARGAR IMÁGENES ===
      imagePullSecrets:
      - name: ghcr-credentials  # <-- El nombre del secreto que creaste
      # ==========================================================
      terminationGracePeriodSeconds: 30
      containers:
      - name: httpd-container
        image: httpd:alpine # Esta imagen será reemplazada por el pipeline
        ports:
        - containerPort: 80
