apiVersion: v1
kind: Service
metadata:
  name: html-app-service-QA
spec:
  selector:
    app: html-appQA  # ¡Corregido para que coincida con el deployment!
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30008 # <-- Puerto para QA
  type: NodePort
