apiVersion: v1
kind: Service
metadata:
  name: html-app-service
spec:
  selector:
    app: html-appQA  # ¡Corregido para que coincida con el deployment!
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
