name: CI/CD Pipeline for k0s with httpd-alpine

on:
  push:
    branches:
      - QA

env:
  # Construye el nombre de la imagen usando el registro de GHCR y el nombre de tu repositorio
  IMAGE_NAME: ghcr.io/${{ github.repository }} 
  KUBE_NAMESPACE: default
  DEPLOYMENT_NAME: html-app
  # ✅ El nombre del contenedor debe coincidir con el de deployment.yaml
  CONTAINER_NAME: httpd-container 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # -- Iniciar sesión en GitHub Container Registry usando tus secrets --
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          # ✅ Usando tus secrets personalizados
          username: ${{ secrets.USERGH }}
          password: ${{ secrets.GHCR_TOKEN }}

      # -- Construir y subir la imagen Docker --
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Etiqueta la imagen con el hash del commit para una versión única
          tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: |
            org.opencontainers.image.source=${{ github.repositoryUrl }}
            org.opencontainers.image.revision=${{ github.sha }}

      # -- Configuración de Kubectl (sin cambios) --
      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          chmod 600 ~/.kube/config
          kubectl cluster-info
          kubectl get nodes

      # -- Desplegar en Kubernetes --
      - name: Deploy to Kubernetes
        run: |
          # 1. Aplicar los manifiestos de Kubernetes
          kubectl apply -f deployment.yaml -f service.yaml
          
          # 2. Actualizar la imagen del Deployment con la que acabamos de subir
          # ✅ Usando el CONTAINER_NAME correcto
          kubectl set image deployment/$DEPLOYMENT_NAME $CONTAINER_NAME=${{ env.IMAGE_NAME }}:${{ github.sha }} --record
          
          # 3. Verificar el despliegue
          echo "Waiting for deployment rollout to finish..."
          kubectl rollout status deployment/$DEPLOYMENT_NAME
          echo "Deployment successful! Pods list:"
          kubectl get pods -n $KUBE_NAMESPACE
