name: CI/CD Pipeline

on:
  #push:
    branches:
      - master  # Cambia a la rama que estés utilizando

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub #cambiar despues
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t liyo13/build-push-actions:latest .
        docker push liyo13/build-push-actions:latest

    - name: Install kubectl
      uses: azure/setup-kubectl@v3

    - name: Configure kubeconfig
      run: |
        echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml

    - name: Deploy to Kubernetes
      run: |
<<<<<<< HEAD
        kubectl apply -f deployment.yaml
=======
        kubectl apply -f deployment.yaml
>>>>>>> 78a7426871e4fc071cc53d47ba2469a5a01c9146
